plugins:
  - stylelint-scss
extends:
  - stylelint-config-standard
  - ./node_modules/prettier-stylelint/config.js
rules:
  at-rule-no-unknown: null
  selector-pseudo-class-no-unknown: null
  no-descending-specificity: null
  no-duplicate-selectors: null
  indentation: 2
  string-quotes: single
  color-hex-case: lower
  color-hex-length: short
  color-named: never
  selector-combinator-space-after: always
  selector-attribute-quotes: always
  selector-attribute-operator-space-before: never
  selector-attribute-operator-space-after: never
  selector-attribute-brackets-space-inside: never
  declaration-colon-space-before: never
  declaration-colon-space-after: always
  number-leading-zero: never
  function-url-quotes: never
  font-family-name-quotes: always-where-recommended
  comment-whitespace-inside: always
  comment-empty-line-before: always
  at-rule-no-vendor-prefix: true
  selector-pseudo-element-colon-notation: double
  selector-pseudo-class-parentheses-space-inside: never
  selector-no-vendor-prefix: true
  media-feature-range-operator-space-before: always
  media-feature-range-operator-space-after: always
  media-feature-parentheses-space-inside: never
  media-feature-name-no-vendor-prefix: true
  media-feature-colon-space-before: never
  media-feature-colon-space-after: always
